# Generated by Django 4.1.2 on 2022-11-02 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BodySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('body_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotterapi.bodypart')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image_url', models.TextField()),
                ('video_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('created_on', models.DateTimeField()),
                ('profile_image_url', models.TextField()),
                ('active', models.BooleanField(verbose_name=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotterapi.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotterapi.session')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='exercises',
            field=models.ManyToManyField(through='spotterapi.SessionExercise', to='spotterapi.exercise'),
        ),
        migrations.AddField(
            model_name='session',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotterapi.plan'),
        ),
        migrations.AddField(
            model_name='session',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotterapi.profile'),
        ),
        migrations.CreateModel(
            name='PlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotterapi.exercise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotterapi.plan')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='exercises',
            field=models.ManyToManyField(through='spotterapi.PlanExercise', to='spotterapi.exercise'),
        ),
        migrations.AddField(
            model_name='plan',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotterapi.profile'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotterapi.machine'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotterapi.type'),
        ),
        migrations.AddField(
            model_name='bodypart',
            name='body_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotterapi.bodysection'),
        ),
    ]
