# Generated by Django 4.1.2 on 2022-11-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotterapi', '0003_session_from_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='from_plan',
        ),
        migrations.RemoveField(
            model_name='session',
            name='profile',
        ),
        migrations.AddField(
            model_name='plan',
            name='stand_alone',
            field=models.BooleanField(default=1, verbose_name=False),
            preserve_default=False,
        ),
    ]
