# Generated by Django 4.1.2 on 2022-11-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotterapi', '0005_rename_exercises_session_session_exercises'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_exercises',
            new_name='exercises',
        ),
    ]
