# Generated by Django 4.1.2 on 2022-11-02 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotterapi', '0006_rename_session_exercises_session_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='body_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spotterapi.bodysection'),
            preserve_default=False,
        ),
    ]
